name: ruffnote-plus
description: A sample Dart Chrome packaged application
dependencies:
  chrome: '>=0.6.1 <0.7.0'
  polymer: '>=0.15.1 <0.15.2'
dev_dependencies:
  archive: '>=1.0.16 <1.1.0'
  chrome_testing: '>=0.1.0 <0.2.0'
  grinder: '>=0.6.0 <0.7.0'
  intl: any
  path: any
  unittest: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    csp: true
    entry_points:
    - web/index.html
